Tech.Web/Models/ErrorViewModel.cs
using System;

namespace Tech.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tech.Web/Models/Project.cs
namespace Tech.Web.Models
{
    public class Project
    {
        public string Route { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Creator { get; set; }
        
    }
}

Tech.Web/Models/ProjectsViewModel.cs
using System.Collections.Generic;

namespace Tech.Web.Models
{
    public class ProjectsViewModel
    {
        public List<Project> Projects { get; set; } = new List<Project>();
    }
}

Tech.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Tech.Web.Models;

namespace Tech.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tech.Web/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Tech.Web.Models;

namespace Tech.Web.Controllers
{
    public class ProjectsController : Controller
    {
        public IActionResult Index()
        {
            var vm = new ProjectsViewModel();
            
            vm.Projects.Add(new Project()
            {
                Route = "https://sahelpinghands.org",
                Name = "Helping Hands",
                Description = "Full-Stack Capstone project rendered utilizing SpringBoot, Java, Spring Security, Thymeleaf and SASS/SCSS for styling.",
                Type = "Donation Forum/Database Rendering",
                Creator = "Lening Rodas, Christian Parker, Evan Mead, John Brooks"

            });            

            vm.Projects.Add(new Project()
            {
                Route = "/weathermap/weather_map.html",
                Name = "WeatherNova",
                Description = "Weather app made using API calls to the OpenWeatherMap API; Renders instant 7-day forecast upon location selection.",
                Type = "API Calls and MapRendering",
                Creator = "John Brooks"

            });

            vm.Projects.Add(new Project()
            {
                Route = "https://github.com/SFW-FreeDevelopment/LordOfFrames",
                Name = "Lord Of Frames",
                Description = "AI Bot created for use in Discord Server using .NET 6/C#. Outputs instant data responses for real-time command requests.",
                Type = "Machine Programming",
                Creator = "Christopher Plummer, John Brooks"

            });
            
            vm.Projects.Add(new Project()
            {
                Route = "/movie-app/index.html",
                Name = "Six Degrees of Sandler",
                Description = "API Requests using IMDB to enable CRUD, Search functionality within local database.",
                Type = "API/Querying Functionality",
                Creator = "John Brooks, Christian Parker"
            
            });
            
            vm.Projects.Add(new Project()
            {
                Route = "/nemesis-engage-2/index.html",
                Name = "NE: 2",
                Description = "Turn-based fighting system demo created utilizing HTML, CSS, JS and jQuery. Expanded roster from 2 to 30 characters utilizing JSON object for enhanced fighting mechanics.",
                Type = "Fully Static Video Game",
                Creator = "John Brooks"

            });

            vm.Projects.Add(new Project()
            {
                Route = "/coffee-project/index.html",
                Name = "Boom! Roasted",
                Description = "Coffee Ordering Project. Michael Scott-themed.",
                Type = "Static Ordering Functionality",
                Creator = "John Brooks, Connor Wulf"
            
            });

            return View(vm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tech.Web/Views/Home/Index.cshtml
  @section Styles {
        <link rel="stylesheet" href="~/css/home.css">
    }
<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.1/less.min.js"></script>

@{
    ViewData["Title"] = "John Brooks";
}
  
  <div class="card front">
    <div class="blue"></div>
    <div class="yellow"></div>
    <div class="pink"></div>
    <div class="dots"></div>
    <div class="personal-intro">
      <p>John Brooks</p>
      <p>Software Developer</p>
    </div>
  </div>
  <div class="card back">
    <div class="yellow"></div>
    <div class="top dots"></div>
    <div class="personal-info">
      <p>Full-Stack</p>
      <p>HTML/CSS/JS/jQuery</p>
      <p>Java/MySQL/SpringBoot</p>
      <p>C#/.NET Core</p>
      <p>React/Angular</p>
    </div>
    <div class="logo-links">
      <a href="https://www.github.com/johnbrooks92" alt="GitHub" target="_blank"><img src="img/GitHub-Mark-32px.png"></a>
      <a href="https://www.linkedin.com/in/john-brooks-/" alt="LinkedIn" target="_blank"><img src="img/linkedin_32px_black.png"></a>
      <a asp-area="" asp-controller="Projects" asp-action="Index" alt="My Projects" target="_blank"><img src="img/open-folder.png"></a>
      <a href="img/John.Brooks_Resume.pdf" download="John.Brooks_Resume.pdf"><img src="img/pdf-icon.png" alt="My Resume" width="32" height="32"></a>
      <a href="mailto:johntbrooks92@gmail.com"><img src="img/email-icon.png" alt="Email Me" width="32" height="32"></a>
    </div>
    <div class="bottom dots"></div>
    <div class="pink"></div>
  </div>
  
  

Tech.Web/Views/Projects/Index.cshtml
@model ProjectsViewModel

    @section Styles {
        <link rel="stylesheet" href="~/css/project.css">
    }
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400" rel="stylesheet">
     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />


@{
    ViewData["Title"] = "My Projects";
}

<div class="text-center">
    <h1 class="display-4">John's Portfolio</h1>
    <p>Select one of my projects below to view.</p>
</div>
<br/>
<div class="container-fluid row">
    @foreach (var project in Model.Projects)
    {
    @*     <div class="col-3"> *@
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-4">
            <a href="@project.Route" style="text-decoration:none" target="_blank">
                <div class="card">
                    <div class="projectTitle">
                        <h5 class="title">@project.Name</h5>
                    </div>
                    <div class="projectInfo">
                        <p>@project.Description</p>
                        <p>@project.Type</p>
                        <p>Developers: @project.Creator</p>
                    </div>
                    <div class="bar">
                        <div class="emptybar"></div>
                        <div class="filledbar"></div>
                    </div>
                </div>
            </a>
        </div>
    }
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

Tech.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tech.Web</title>
    @RenderSection("Styles", required: false)
</head>
<body>
    
            @RenderBody()

  

</body>
</html>